DROP TABLE  MOVIMENTI_OFFERTA  CASCADE;

DROP TABLE MOVIMENTI_LOCALE CASCADE;

DROP TABLE DETTAGLIO_PAGAMENTO CASCADE;

DROP TABLE PAGAMENTO CASCADE;

DROP TABLE OFFERTA CASCADE;

DROP TABLE LOCALE CASCADE;

DROP TABLE POSIZIONE CASCADE;

DROP TABLE GESTORE CASCADE;

DROP TABLE PRODOTTO CASCADE;

DROP TABLE UTENTE CASCADE;

DROP TABLE MOVIMENTI_OFFERTA_AUD CASCADE;

DROP TABLE REVINFO CASCADE;