CREATE TABLE PRODOTTO ( ID BIGINT NOT NULL AUTO_INCREMENT, DESCRIZIONE VARCHAR (140), IMMAGINE BLOB, PRIMARY KEY(ID));

CREATE TABLE GESTORE ( ID BIGINT NOT NULL AUTO_INCREMENT, NOME VARCHAR(149), MAIL VARCHAR(140), PRIMARY KEY(ID));

CREATE TABLE POSIZIONE ( ID BIGINT NOT NULL AUTO_INCREMENT, LONGITUDINE DOUBLE, LATITUDINE DOUBLE, INDIRIZZO VARCHAR(140), NUMERO VARCHAR(10), CITTA VARCHAR(40), CAP VARCHAR(40), PRIMARY KEY(ID));

-- CON IL CONSTRAINT UNIQUE SI VUOLE RAFFORZARE IL CONCETTO ONE-TO-ONE TRA LOCALE E POSIZIONE
CREATE TABLE LOCALE( ID BIGINT NOT NULL AUTO_INCREMENT, ID_POSIZIONE BIGINT UNIQUE NOT NULL, ID_GESTORE BIGINT NOT NULL, NOME VARCHAR(140), LOGO BLOB, DESCRIZIONE VARCHAR(140), FIDELIZZAZIONE BOOLEAN NOT NULL DEFAULT FALSE, PRIMARY KEY(ID), FOREIGN KEY (ID_POSIZIONE) REFERENCES POSIZIONE(ID), FOREIGN KEY (ID_GESTORE) REFERENCES GESTORE(ID) ON DELETE CASCADE);


CREATE TABLE OFFERTA ( ID BIGINT NOT NULL AUTO_INCREMENT, TITOLO VARCHAR(140), DESCRIZIONE VARCHAR(140), ID_PRODOTTO BIGINT, DATA_INIZIO DATETIME, DATA_FINE DATETIME, QUANTITA INT, PREZZO_UNITARIO_PIENO DECIMAL(4,2), PREZZO_UNITARIO_SCONTATO DECIMAL(4,2) ,ID_LOCALE BIGINT, STATO_OFFERTA VARCHAR(10), PRIMARY KEY (ID), FOREIGN KEY (ID_LOCALE) REFERENCES LOCALE(ID) ON DELETE CASCADE, FOREIGN KEY (ID_PRODOTTO) REFERENCES PRODOTTO(ID) ON DELETE CASCADE);

CREATE TABLE UTENTE ( ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, ID_TELEFONO VARCHAR(255) NOT NULL UNIQUE, TIPO_TELEFONO VARCHAR(100) NOT NULL);

CREATE TABLE MOVIMENTI_LOCALE ( ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, ID_UTENTE BIGINT NOT NULL, STATO VARCHAR(100) NOT NULL, ID_LOCALE BIGINT NOT NULL, CONSTRAINT UNIQUE_MOV_LOC UNIQUE (ID_UTENTE, STATO, ID_LOCALE), FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID), FOREIGN KEY (ID_LOCALE) REFERENCES LOCALE(ID) ON DELETE CASCADE);

CREATE TABLE MOVIMENTI_OFFERTA ( ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, ID_UTENTE BIGINT NOT NULL, STATO VARCHAR(100) NOT NULL, ID_OFFERTA BIGINT NOT NULL, CONSTRAINT UNIQUE_MOV_OFF UNIQUE (ID_UTENTE, STATO, ID_OFFERTA), FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID), FOREIGN KEY (ID_OFFERTA) REFERENCES OFFERTA(ID) ON DELETE CASCADE);

-- AUDIT TIMESTAMP GLOBALE
CREATE TABLE REVINFO (REV INTEGER NOT NULL AUTO_INCREMENT, REVTSTMP BIGINT, PRIMARY KEY (REV));

-- AUDIT MOVIMENTO OFFERTA
CREATE TABLE MOVIMENTI_OFFERTA_AUD (ID BIGINT NOT NULL, REV INTEGER NOT NULL, REVTYPE TINYINT, ID_OFFERTA BIGINT, STATO VARCHAR(100), ID_UTENTE BIGINT, PRIMARY KEY (ID, REV), FOREIGN KEY (REV) REFERENCES REVINFO(REV));

CREATE TABLE PAGAMENTO ( ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, ID_GESTORE BIGINT NOT NULL, ID_PAYPAL_PAYMENT VARCHAR(140), ID_PAYPAL_PAYER VARCHAR(140), TITOLO_ACQUISTO VARCHAR(140), DATA_PAGAMENTO DATETIME, IMPORTO_TOTALE DECIMAL(4,2), FOREIGN KEY (ID_GESTORE) REFERENCES GESTORE(ID));

CREATE TABLE DETTAGLIO_PAGAMENTO ( ID_PAGAMENTO BIGINT NOT NULL, ID_OFFERTA BIGINT NOT NULL UNIQUE, FOREIGN KEY (ID_PAGAMENTO) REFERENCES PAGAMENTO(ID) ON DELETE CASCADE, FOREIGN KEY (ID_OFFERTA) REFERENCES OFFERTA(ID), PRIMARY KEY (ID_PAGAMENTO, ID_OFFERTA));